name: Build & Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests & Build
      run: ./gradlew build
    - name: Clean 
      run: ./gradlew clean
    
